// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ofhcjjajscwutppzinun.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9maGNqamFqc2N3dXRwcHppbnVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxOTA0MjMsImV4cCI6MjA2OTc2NjQyM30.qghpZLVHt_QAjhtgbtcZ3GB5YSbCebtXVLM_AmgnWyM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});